name: college_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  typewritertext: ^3.0.3
  auto_size_text: ^3.0.0
  dotted_border: ^2.1.0
  page_transition: ^2.1.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - images/
    - animations/

