name: college_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  typewritertext: ^3.0.3
  auto_size_text: ^3.0.0
  dotted_border: ^2.1.0
  page_transition: ^2.1.0
  lottie: ^3.1.0
  holding_gesture: ^1.2.0
  awesome_snackbar_content: ^0.1.3
  speech_to_text: ^6.6.1
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - images/
    - animations/

